### ISSUE TITLE
Variables declaration

### ISSUE THREAD

**Issue by joelepore** [lt-scuolalavoro/suit#24]
Should a variable that is used only in a function be declared in the main?

**Comment by RobertoClemente25** [comment]
I don't think so, unless that variable is used in multiple functions, but then it shouldn't be declared in the main, but outside every function
Example:
#include "stdio.h"

Int x = 0;

void myFunc(int);

void main(){
    myFunc(5);
    printf("x is %d", &x);
}

void myFunc(int newValue){
    x = newValue;
}
