### ISSUE TITLE
Controllare l'input della data

### ISSUE THREAD

**Issue by joelepore** [lt-scuolalavoro/suit#32]
L'utente deve inserire la data nel formato gg-mm-aaaa. 
Nel database bisogna salvare la stessa data nel formato aaaa-mm-gg.
Controllare l'input della data in modo che venga inserita nel database con il giusto formato, anche nel caso in cui l'utente inserisca la data in un altro formato.

**Comment by ItHurtsLikeHell** [comment]
look at the issues number 33
