### ISSUE TITLE
DB versioning general fixes

### ISSUE THREAD

**Issue by mmissiato** [lt-scuolalavoro/suit#70]
1. Which engine are you using? InnoDB or MyISAM? I suppose the first one but it's better to specify it on table creation.

2. Can you move "USE suit" (maybe) in bash script and left only operational queries in sqls? Or we can use . notation to refer to the tables.

3. Add conditions on version table updating to be less prone to mistakes. You have to be sure to update the current value and it has to be a +1 incremental update.  The statement should look like this:
UPDATE `suit.version` SET `db_version`=n  WHERE `db_version`=n-1 LIMIT 1;

4. I'd prefer to rename db_version to just version.

5. In general, pay attention to conventions, e.g., key words must be capital.

**Comment by ItHurtsLikeHell** [comment]
**4.** do you mean that instead of calling it _db_version_ we should call e.g. _4_?

**Comment by mmissiato** [comment]
Rename the field from _db_version_ to _version_

**Comment by ItHurtsLikeHell** [comment]
**1.** What do you mean with _specify it on table creation_?

**Comment by mmissiato** [comment]
@ItHurtsLikeHell http://lmgtfy.com/?q=mysql+specify+engine+on+table+creation

**Comment by ItHurtsLikeHell** [comment]
I added the info about the engine even if in my opinion it is useless since in automatic, if not specified, it is classified as InnoDB
