### ISSUE TITLE
Move sql folder to the upper level

### ISSUE THREAD

**Issue by mmissiato** [lt-scuolalavoro/suit#71]
I'd prefer to have sql folder to the same level of www

**Comment by ItHurtsLikeHell** [comment]
do you mean moving from _suit/src_ to the main folder ( _suit_ ) ?

**Comment by mmissiato** [comment]
Yes.

**Comment by ItHurtsLikeHell** [comment]
I had an idea. we could make a folder called changes which contains other subdirectories like sql, so I can add another .sh file which is started by db_update.sh ( i.g. an sh to move the sql folder )

**Comment by mmissiato** [comment]
Call "changes" a folder looks too general other than unconventional. Moreover, it adds complexity to folder tree without adding benefits. Also, the second .sh would do something that the first sh can already do. So, why should we have 2 of them? Let's keep things simple.
